import type { Metadata } from "next";
import React from 'react';
import Header from '@/layout/header';
import Footer from '@/layout/footer';
import Aside from '@/layout/aside';
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header/>
        <div className="grid grid-cols-[350px_1fr] gap-4">
          <Aside>{}</Aside>
          <main>{children}</main>
        </div>
        <Footer/>
      </body>
    </html>
  );
}
